name: power6_mobile
description: A productivity app focused on task tracking, streaks, and timeline history.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.2

  # State Management (optional, prep for Provider)
  provider: ^6.1.2

  # Date and Time Utilities
  intl: ^0.19.0

  # HTTP (for API services)
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
