name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git curl unzip xz-utils zip libglu1-mesa

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          cache: true

      - name: Flutter pub get
        working-directory: power6_mobile
        run: flutter pub get

      - name: Build Flutter Web (release)
        working-directory: power6_mobile
        run: flutter build web --release

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POWER6 }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
